# Generated by Django 5.1.4 on 2025-01-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_option', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='WeekMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('side_dish', models.CharField(max_length=165)),
                ('date_meal', models.DateTimeField()),
                ('image_meal', models.ImageField(blank=True, default='', upload_to='menu/week_menu/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_option_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekmenu_option_1', to='menu.options')),
                ('name_option_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekmenu_option_2', to='menu.options')),
                ('name_option_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekmenu_option_3', to='menu.options')),
            ],
        ),
    ]
