# Generated by Django 5.1.4 on 2025-01-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_weekmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekmenu',
            name='image_meal',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
