# Generated by Django 5.1.4 on 2025-01-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_weekmenu_image_meal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeekMenu',
        ),
    ]
