# Generated by Django 5.1.4 on 2025-01-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_weekmenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeekMenu',
        ),
    ]
