# Generated by Django 5.1.4 on 2025-01-09 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_weekmenu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=65, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=65, verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=65, verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name': 'Opção', 'verbose_name_plural': 'Opções'},
        ),
        migrations.AlterModelOptions(
            name='weekmenu',
            options={'verbose_name': 'Cardápio semanal', 'verbose_name_plural': 'Cardápio semanal'},
        ),
        migrations.AlterField(
            model_name='weekmenu',
            name='date_meal',
            field=models.DateField(verbose_name='Data da refeição'),
        ),
        migrations.AlterField(
            model_name='weekmenu',
            name='image_meal',
            field=models.ImageField(blank=True, default='', upload_to='menu/week_menu/%Y/%m/%d/', verbose_name='Foto do prato'),
        ),
        migrations.AlterField(
            model_name='weekmenu',
            name='name_option_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekmenu_option_1', to='menu.options', verbose_name='Opção 1'),
        ),
        migrations.AlterField(
            model_name='weekmenu',
            name='name_option_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekmenu_option_2', to='menu.options', verbose_name='Opção 2'),
        ),
        migrations.AlterField(
            model_name='weekmenu',
            name='name_option_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekmenu_option_3', to='menu.options', verbose_name='Opção 3'),
        ),
        migrations.AlterField(
            model_name='weekmenu',
            name='side_dish',
            field=models.CharField(max_length=165, verbose_name='Guarnição'),
        ),
        migrations.AlterField(
            model_name='weekmenu',
            name='title',
            field=models.CharField(max_length=65, verbose_name='Prato Principal'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=65, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=65, verbose_name='Sobrenome')),
                ('birth_date', models.DateField(verbose_name='Data de nasc.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_company', to='menu.company', verbose_name='Empresa')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='menu.company', verbose_name='Perfil')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_shift', to='menu.shift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
