# Generated by Django 5.1.4 on 2025-01-10 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_company_profile_shift_alter_options_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='menu.profile', verbose_name='Perfil'),
        ),
        migrations.CreateModel(
            name='MealChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('meal_option', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_choices', to='menu.employee')),
            ],
            options={
                'unique_together': {('employee', 'meal_date')},
            },
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.weekmenu')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.options')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'menu')},
            },
        ),
    ]
