# Generated by Django 5.1.4 on 2025-01-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_userchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekmenu',
            name='name_option_1',
        ),
        migrations.RemoveField(
            model_name='weekmenu',
            name='name_option_2',
        ),
        migrations.RemoveField(
            model_name='weekmenu',
            name='name_option_3',
        ),
        migrations.AddField(
            model_name='weekmenu',
            name='options',
            field=models.ManyToManyField(related_name='weekmenu_options', to='menu.options', verbose_name='Opções'),
        ),
    ]
