# Generated by Django 5.1.4 on 2025-01-16 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_remove_weekmenu_name_option_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.weekmenu')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.options')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
