# Generated by Django 5.1.4 on 2025-01-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_menuoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_on_vacations',
            field=models.BooleanField(default=False, verbose_name='Férias'),
        ),
    ]
