# Generated by Django 5.1.4 on 2025-01-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_unity_employee_unity'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_day_vacations',
            field=models.DateField(blank=True, null=True, verbose_name='Ínicio Férias'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_home_office',
            field=models.BooleanField(default=False, verbose_name='Home Office'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_day_vacations',
            field=models.DateField(blank=True, null=True, verbose_name='Final Férias'),
        ),
    ]
