# Generated by Django 5.1.4 on 2025-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_employee_first_day_vacations_employee_is_home_office_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuoption',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuoption',
            name='option',
        ),
        migrations.CreateModel(
            name='PreviousWeekMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65, verbose_name='Prato Principal')),
                ('side_dish', models.CharField(max_length=165, verbose_name='Guarnição')),
                ('date_meal', models.DateField(verbose_name='Data da refeição')),
                ('image_meal', models.ImageField(blank=True, default='', upload_to='menu/previous_week_menu/%Y/%m/%d/', verbose_name='Foto do prato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('options', models.ManyToManyField(related_name='previous_week_menu_options', to='menu.options', verbose_name='Opções')),
            ],
            options={
                'verbose_name': 'Cardápio anterior',
                'verbose_name_plural': 'Cardápios anteriores',
            },
        ),
        migrations.DeleteModel(
            name='MealChoice',
        ),
        migrations.DeleteModel(
            name='MenuOption',
        ),
    ]
