# Generated by Django 5.1.4 on 2025-01-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
