# Generated by Django 5.1.4 on 2025-01-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to='menu.profile', verbose_name='Perfil'),
        ),
    ]
