# Generated by Django 5.1.4 on 2025-02-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_alter_restaurant_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthInvoicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_invoicing_first_day', models.DateField(verbose_name='Primeiro dia da semana')),
                ('week_invoicing_last_day', models.DateField(verbose_name='Último dia da semana')),
                ('month_invoicing', models.CharField(max_length=65, verbose_name='Mês')),
                ('meals_quantity', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_invoicing_company', to='menu.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Relatório mensal',
                'verbose_name_plural': 'Relatório mensal',
            },
        ),
    ]
